// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package gravatar

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GravatarRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravatarRequest) Reset()         { *m = GravatarRequest{} }
func (m *GravatarRequest) String() string { return proto.CompactTextString(m) }
func (*GravatarRequest) ProtoMessage()    {}
func (*GravatarRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *GravatarRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravatarRequest.Unmarshal(m, b)
}
func (m *GravatarRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravatarRequest.Marshal(b, m, deterministic)
}
func (m *GravatarRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravatarRequest.Merge(m, src)
}
func (m *GravatarRequest) XXX_Size() int {
	return xxx_messageInfo_GravatarRequest.Size(m)
}
func (m *GravatarRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GravatarRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GravatarRequest proto.InternalMessageInfo

func (m *GravatarRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GravatarRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GravatarResponse struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GravatarResponse) Reset()         { *m = GravatarResponse{} }
func (m *GravatarResponse) String() string { return proto.CompactTextString(m) }
func (*GravatarResponse) ProtoMessage()    {}
func (*GravatarResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *GravatarResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GravatarResponse.Unmarshal(m, b)
}
func (m *GravatarResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GravatarResponse.Marshal(b, m, deterministic)
}
func (m *GravatarResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GravatarResponse.Merge(m, src)
}
func (m *GravatarResponse) XXX_Size() int {
	return xxx_messageInfo_GravatarResponse.Size(m)
}
func (m *GravatarResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GravatarResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GravatarResponse proto.InternalMessageInfo

func (m *GravatarResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*GravatarRequest)(nil), "gravatar.GravatarRequest")
	proto.RegisterType((*GravatarResponse)(nil), "gravatar.GravatarResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0x2f, 0x4a, 0x2c, 0x4b, 0x2c, 0x49, 0x2c,
	0x52, 0xb2, 0xe6, 0xe2, 0x77, 0x87, 0xb2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44,
	0xb8, 0x58, 0x53, 0x73, 0x13, 0x33, 0x73, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c,
	0x21, 0x21, 0x2e, 0x96, 0xe2, 0xcc, 0xaa, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x30,
	0x5b, 0x49, 0x85, 0x4b, 0x00, 0xa1, 0xb9, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x80, 0x8b,
	0xb9, 0xb4, 0x08, 0xa6, 0x17, 0xc4, 0x34, 0x0a, 0x41, 0x58, 0x11, 0x9c, 0x5a, 0x54, 0x96, 0x99,
	0x9c, 0x2a, 0xe4, 0xc8, 0xc5, 0xe1, 0x9e, 0x9a, 0x97, 0x5a, 0x94, 0x58, 0x92, 0x2a, 0x24, 0xa9,
	0x07, 0x73, 0x8c, 0x1e, 0x9a, 0x4b, 0xa4, 0xa4, 0xb0, 0x49, 0x41, 0xec, 0x49, 0x62, 0x03, 0xfb,
	0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xfc, 0x40, 0x11, 0xd7, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GravatarServiceClient is the client API for GravatarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GravatarServiceClient interface {
	Generate(ctx context.Context, in *GravatarRequest, opts ...grpc.CallOption) (*GravatarResponse, error)
}

type gravatarServiceClient struct {
	cc *grpc.ClientConn
}

func NewGravatarServiceClient(cc *grpc.ClientConn) GravatarServiceClient {
	return &gravatarServiceClient{cc}
}

func (c *gravatarServiceClient) Generate(ctx context.Context, in *GravatarRequest, opts ...grpc.CallOption) (*GravatarResponse, error) {
	out := new(GravatarResponse)
	err := c.cc.Invoke(ctx, "/gravatar.GravatarService/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GravatarServiceServer is the server API for GravatarService service.
type GravatarServiceServer interface {
	Generate(context.Context, *GravatarRequest) (*GravatarResponse, error)
}

// UnimplementedGravatarServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGravatarServiceServer struct {
}

func (*UnimplementedGravatarServiceServer) Generate(ctx context.Context, req *GravatarRequest) (*GravatarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}

func RegisterGravatarServiceServer(s *grpc.Server, srv GravatarServiceServer) {
	s.RegisterService(&_GravatarService_serviceDesc, srv)
}

func _GravatarService_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GravatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravatarServiceServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravatar.GravatarService/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravatarServiceServer).Generate(ctx, req.(*GravatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GravatarService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravatar.GravatarService",
	HandlerType: (*GravatarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _GravatarService_Generate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
